-- 코드를 입력하세요
SELECT R2.FOOD_TYPE, R2.REST_ID, R2.REST_NAME, R1.FAVORITES
FROM (SELECT MAX(FAVORITES) AS FAVORITES, FOOD_TYPE
      FROM REST_INFO
      GROUP BY FOOD_TYPE
      ) AS R1
JOIN REST_INFO R2 ON R1.FAVORITES=R2.FAVORITES AND R1.FOOD_TYPE=R2.FOOD_TYPE
ORDER BY FOOD_TYPE DESC;