-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, CONCAT(CITY, " ", STREET_ADDRESS1, " ", STREET_ADDRESS2) AS '전체주소', 
       CONCAT(SUBSTR(U.TLNO, 1, 3), "-", SUBSTR(U.TLNO, 4, 4), "-", SUBSTR(U.TLNO, 8, 4)) AS '전화번호'
FROM USED_GOODS_USER U
JOIN (SELECT WRITER_ID, COUNT(*) AS WRITE_COUNT
      FROM USED_GOODS_BOARD
      GROUP BY WRITER_ID
     ) AS B
ON U.USER_ID=B.WRITER_ID
WHERE B.WRITE_COUNT>=3
ORDER BY USER_ID DESC;