-- 코드를 입력하세요
# SELECT *
# FROM ANIMAL_OUTS
# ORDER BY ANIMAL_ID;


SELECT O2.ANIMAL_ID, O1.NAME
FROM ANIMAL_OUTS O1
JOIN (SELECT O.ANIMAL_ID, I.NAME
      FROM (SELECT ANIMAL_ID, IFNULL(NAME, 'NO') AS NAME
            FROM ANIMAL_INS) AS I
      RIGHT JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID) AS O2 ON O2.ANIMAL_ID = O1.ANIMAL_ID
WHERE O2.NAME IS NULL
ORDER BY ANIMAL_ID;

