-- 코드를 작성해주세요

SELECT COUNT(*) AS FISH_COUNT, F.FISH_NAME
FROM (SELECT N.FISH_NAME
      FROM FISH_NAME_INFO N
      JOIN FISH_INFO F USING(FISH_TYPE)) AS F
GROUP BY F.FISH_NAME
ORDER BY FISH_COUNT DESC;
