-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, B.PRICE AS TOTAL_SALES 
FROM (SELECT USED_GOODS_BOARD.STATUS, WRITER_ID, SUM(PRICE) AS PRICE
      FROM USED_GOODS_BOARD
      WHERE USED_GOODS_BOARD.STATUS='DONE'
      GROUP BY WRITER_ID) AS B
JOIN USED_GOODS_USER U ON B.WRITER_ID=U.USER_ID
WHERE B.PRICE>=700000
GROUP BY B.WRITER_ID
ORDER BY TOTAL_SALES;