-- 코드를 작성해주세요
SELECT TEST.ITEM_ID, T.ITEM_NAME, T.RARITY
FROM (SELECT T.ITEM_ID
      FROM ITEM_INFO I
      JOIN ITEM_TREE T ON T.PARENT_ITEM_ID=I.ITEM_ID
      WHERE I.RARITY = 'RARE'
     ) AS TEST,
     ITEM_INFO T
WHERE T.ITEM_ID = TEST.ITEM_ID
ORDER BY TEST.ITEM_ID DESC;