-- 코드를 입력하세요
SELECT A.MCDP_CD AS `진료과코드`, COUNT(*) AS `5월예약건수`
FROM (SELECT APNT_YMD, MCDP_CD
      FROM APPOINTMENT
      WHERE YEAR(APNT_YMD) = '2022' AND MONTH(APNT_YMD) = '05') AS A
GROUP BY A.MCDP_CD
ORDER BY `5월예약건수`, `진료과코드`;