-- 코드를 입력하세요
SELECT H.FLAVOR
FROM FIRST_HALF H
JOIN (SELECT FLAVOR
      FROM ICECREAM_INFO
      WHERE INGREDIENT_TYPE='fruit_based') AS F USING(FLAVOR)
WHERE H.TOTAL_ORDER > 3000
ORDER BY H.TOTAL_ORDER DESC;