-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', B.BOARD_ID, "/", F.FILE_ID, F.FILE_NAME, F.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_FILE F USING (BOARD_ID)
WHERE (SELECT MAX(VIEWS)
       FROM USED_GOODS_BOARD
      ) = B.VIEWS
ORDER BY F.FILE_ID DESC;