-- 코드를 작성해주세요

SELECT F1.COUNT AS FISH_COUNT, F2.LENGTH AS MAX_LENGTH, F1.FISH_TYPE
FROM (SELECT COUNT(*) AS COUNT, AVG(IFNULL(LENGTH, 10)) AS LENGTH, FISH_TYPE
       FROM FISH_INFO
       GROUP BY FISH_TYPE
       ) F1
JOIN (SELECT MAX(LENGTH) AS LENGTH, FISH_TYPE
      FROM FISH_INFO
      GROUP BY FISH_TYPE
     ) F2 ON F1.FISH_TYPE = F2.FISH_TYPE
WHERE F1.LENGTH>=33
ORDER BY FISH_TYPE;